import React from "react";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { cleanup,fireEvent,render,waitFor,within } from "@testing-library/react";
import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import type { ProjectDto,WorkspaceReconciliationDto } from "@contextkeep/shared";

let currentPath="/projects/project-1";
const {apiFetchMock}=vi.hoisted(()=>({apiFetchMock:vi.fn()}));
vi.mock("../src/lib/api.js",()=>({apiFetch:apiFetchMock}));
vi.mock("@tanstack/react-router",async()=>{const R=await import("react");return{Link:({to,params,children,...rest}:any)=>R.createElement("a",{href:params?.projectId?to.replace("$projectId",params.projectId):to,...rest},children),Outlet:()=>R.createElement("div",{"data-testid":"route-outlet"},"CENTER"),useLocation:()=>({pathname:currentPath})}});
const {AppShell}=await import("../src/components/AppShell.js");
const project:ProjectDto={id:"project-1",name:"unihub-retail",aliases:[],parentId:null,description:null,lifecycle:"active",lifecycleRecordId:null,revision:1,createdAt:"2026-09-10T00:00:00.000Z",updatedAt:"2026-09-11T08:00:00.000Z"};
const reconciliation:WorkspaceReconciliationDto={generatedAt:"2026-09-11T09:00:00.000Z",total:1,tracked:1,linked:0,ignored:0,unresolved:0,codexCatalogAvailable:true,dshCatalogAvailable:true,seededProjectIds:[],items:[{workspace:{id:"workspace-1",canonicalKey:"git:x",canonicalPath:"/opt/Mobiup/unihub-retail",displayName:"unihub-retail",gitRemote:"github.com/anervalens-netizen/unihub-retail",gitBranch:"main",gitHeadSha:"abc",lastGitActivity:"2026-09-11T08:30:00.000Z",lastObservedActivity:"2026-09-11T08:30:00.000Z",projectId:"project-1",projectName:"unihub-retail",projectLifecycle:"active",ignored:false,firstSeenAt:"2026-09-10T00:00:00.000Z",lastSeenAt:"2026-09-11T09:00:00.000Z",createdAt:"2026-09-10T00:00:00.000Z",updatedAt:"2026-09-11T09:00:00.000Z"},status:"tracked",history:{codexCurrentCount:231,codexArchivedCount:3,codexSummaryCount:29,dshSessionCount:129,lastAgentActivity:"2026-09-11T09:00:00.000Z"},suggestion:{action:null,projectId:null,projectName:null,confidence:null,reason:null}}]};
function mount(options:{showInstall?:boolean;onInstall?:()=>Promise<void>}={}){const q=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<QueryClientProvider client={q}><AppShell authenticated showInstall={options.showInstall??false} installGateReason="" onInstall={options.onInstall??vi.fn(async()=>undefined)} onLogout={vi.fn(async()=>undefined)} onDeleteLocalData={vi.fn(async()=>({status:"complete" as const,summary:{queued:0,inFlight:0,conflicts:0,unknownOutcome:0,reviewRequired:0,unsafeCount:0},errors:[] as [],removedCaches:[]}))}/></QueryClientProvider>)}
beforeEach(()=>{currentPath="/projects/project-1";localStorage.clear();apiFetchMock.mockReset();apiFetchMock.mockImplementation(async(url:string)=>url==="/api/projects"?[project]:url==="/api/workspaces/reconciliation"?reconciliation:Promise.reject(new Error(`unexpected ${url}`)))});afterEach(cleanup);

describe("M4.3/M4.4 review-safe shell",()=>{
 it("mounts exactly one routed subtree and keeps the center shrinkable",async()=>{mount();expect(document.querySelectorAll('[data-testid="route-outlet"]')).toHaveLength(1);const shell=document.querySelector('[data-shell="app"]') as HTMLElement;expect(shell).toBeTruthy();expect(shell.getAttribute("style")).toContain("minmax(0,1fr)");await waitFor(()=>expect(document.querySelector('[data-pane="navigation"] a[href="/projects/project-1"]')).toBeTruthy())});
 it("remembers sidebar project opens for PWA relaunch",async()=>{mount();const nav=document.querySelector('[data-pane="navigation"]') as HTMLElement;const link=await waitFor(()=>{const x=within(nav).getAllByRole("link").find((a)=>a.getAttribute("href")==="/projects/project-1");if(!x)throw new Error("missing project link");return x},{timeout:8000});fireEvent.click(link);expect(localStorage.getItem("ck:last-project")).toBe("project-1")});
 it("surfaces the PWA install action immediately when the browser offers it",async()=>{const onInstall=vi.fn(async()=>undefined);mount({showInstall:true,onInstall});const mobile=document.querySelector('[data-shell="mobile"]') as HTMLElement;const install=within(mobile).getByRole("button",{name:"Install ContextKeep"});fireEvent.click(install);await waitFor(()=>expect(onInstall).toHaveBeenCalledTimes(1))});
 it("keeps the navigation drawer inert while closed and closable from its header",()=>{mount();const navDrawer=document.querySelector('[data-drawer="navigation"]') as HTMLElement;expect(navDrawer.getAttribute("aria-hidden")).toBe("true");expect(navDrawer.hasAttribute("inert")).toBe(true);const mobile=document.querySelector('[data-shell="mobile"]') as HTMLElement;fireEvent.click(within(mobile).getByRole("button",{name:"Open navigation"}));expect(navDrawer.getAttribute("aria-hidden")).toBe("false");fireEvent.click(within(navDrawer).getByRole("button",{name:"Close navigation"}));expect(navDrawer.getAttribute("aria-hidden")).toBe("true");expect(document.querySelector('[data-drawer="agent"]')).toBeNull()});
 it("does not call internal chat APIs from the review-safe shell",async()=>{mount();await waitFor(()=>expect(apiFetchMock.mock.calls.length).toBeGreaterThan(0));expect(apiFetchMock.mock.calls.some((c)=>String(c[0]).startsWith("/api/agent"))).toBe(false)});
});
